# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TheSeven7' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TheSeven7
  pod 'PMSuperButton'
  target 'TheSeven7Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TheSeven7UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
